--- #YAML:1.0
name:               Apache-TS-AdminClient
version:            0.02
abstract:           a perl interface to the statistics and configuration settings stored within Apache Traffic Server.
author:
    - Traffic Server Dev Team <dev@trafficserver.apache.org>
license:            apache
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:              0
    IO::Select:        0
    IO::Socket::UNIX:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
